FROM ruby:3.0.0 as bilder
WORKDIR /usr/src/app
COPY Gemfile Gemfile.lock ./
RUN bundle install


FROM ruby:3.0.0-alpine
ENV APP_HOME /app
RUN mkdir $APP_HOME
WORKDIR $APP_HOME
COPY --from=bilder /usr/src/app $APP_HOME
#RUN apk add --update build-base libffi-dev
RUN bundle check || bundle install
CMD ["bundle", "exec", "jekyll", "serve"]
